### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by luluforever** [Ethan-yt/sept#1]
您好，在运行你的代码的时候显示没有GPU可用，但是实际上我电脑上有啊，之前跑bert都没问题，显示如下：
Warning: There's no GPU available on this machine,training will be performed on
CPU.
请问是什么原因呢？

**Comment by luluforever** [comment]
已经解决，谢谢啦，是参数没配置python train.py -c config/sept.json -d **[gpu]**

**Comment by luluforever** [comment]
已经解决，谢谢啦，是gpu参数没配置python train.py -c config/sept.json -d [gpu]

**Comment by Ethan-yt** [comment]
Thanks for your interest in our work. This issue will be closed.
